### ISSUE TITLE
how to uses private Github repository as cloud storage ?

### ISSUE THREAD

**Issue by tonglei100** [btk/memo#15]
Github's private repository is free, why not use it as cloud storage? thans you

**Comment by btk** [comment]
Hey, at the time of building this private repositories was not free, and for the api to control a private repository, you needed to ask for control of all the private repositories of the github user. (I think they made it individual now, not sure)

Gists looked like a obv choice at the time, but if you would like to contribute, or turn this into private repo based, feel free to fork. I can even give you a hand cheers :)
