### ISSUE TITLE
Can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by roybarber** [btk/memo#7]
MacOS Catalina 10.15.2

When downloading direct from memo website and draging and dropping app to applications after opening the dmg. 

<img width="420" alt="Screenshot 2020-01-07 at 17 15 43" src="https://user-images.githubusercontent.com/2923782/71914385-6bed4a00-3171-11ea-9bc8-f0b9b592cda9.png">

**Comment by btk** [comment]
Hey @roybarber I'm not sure if this is a classic MacOS security prompt, (right click and open for the first time) or a new Catalina thing.

If they changed the prompt text on Catalina, you will need to right click and click `open` to the downloaded `.dmg` file instead of double clicking or opening it with enter, than it will prompt you with an "Open" button.

If not, its a Catalina problem let me install Catalina to look into it.

**Comment by btk** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/5216601/71954010-f3c86800-31f4-11ea-8e73-a3ac5bf4ff77.png)

Ok I saw this, I think I need to update the binary!

**Comment by btk** [comment]
@roybarber I think I fixed it and tested on Catalina,

Would you also give the new version a try: https://usememo.com/MemoSetup.dmg

**Comment by roybarber** [comment]
I've removed it using cleanmymac then downloaded/installed but get the same. 

<img width="512" alt="Screenshot 2020-01-08 at 10 11 01" src="https://user-images.githubusercontent.com/2923782/71969898-7d7d3300-31ff-11ea-8ef7-3c240ac74211.png">

**Comment by btk** [comment]
@roybarber It was way more complicated than I expected. You will also need to Notarize the app using Apple etc. Thanks to: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

![Screenshot at Jan 08 15-30-01](https://user-images.githubusercontent.com/5216601/71978307-0742f580-322c-11ea-9a9f-730d7b742ddd.png)

Now took another build and uploaded the binary to the same link I gave in the other comment. Would you be able to check if it works now, I know it is getting much more to ask. 

I'm not sure why first build worked without problem on my Catalina.

**Comment by roybarber** [comment]
Works! 

<img width="550" alt="Screenshot 2020-01-08 at 14 21 57" src="https://user-images.githubusercontent.com/2923782/71985423-7fa4b900-3222-11ea-98fd-561871a48b22.png">
<img width="1043" alt="Screenshot 2020-01-08 at 14 23 38" src="https://user-images.githubusercontent.com/2923782/71985433-82071300-3222-11ea-934c-ffeef8d6885e.png">
