### ISSUE TITLE
A few typos in the description

### ISSUE THREAD

**Issue by ummahusla** [btk/memo#9]
Like `exiting`, etc

![image](https://user-images.githubusercontent.com/2536096/72264666-02f34f80-3613-11ea-9a29-eabee6a51063.png)

**Comment by btk** [comment]
To be honest I was sleepy while typing that :)

Fixed it on https://github.com/btk/memo/commit/fa76ddc9d117d9f942a965c6c5ed784cf03482a6

Ty for pointing it out!
